"""Initial migration

Revision ID: 4ab810f9beb5
Revises: add_split_screen_to_photo
Create Date: 2024-06-12 20:04:25.161696

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ab810f9beb5'
down_revision = 'add_split_screen_to_photo'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('device',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_name', sa.String(length=100), nullable=False),
    sa.Column('device_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('ip_address', sa.String(length=50), nullable=False),
    sa.Column('photo_update_frequency', sa.Integer(), nullable=True),
    sa.Column('random_order', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('photo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('photo_name', sa.String(length=100), nullable=False),
    sa.Column('path', sa.String(length=200), nullable=False),
    sa.Column('rotation', sa.Integer(), nullable=True),
    sa.Column('scaling', sa.Integer(), nullable=True),
    sa.Column('window_x', sa.Integer(), nullable=True),
    sa.Column('window_y', sa.Integer(), nullable=True),
    sa.Column('split_screen_x', sa.Integer(), nullable=True),
    sa.Column('split_screen_y', sa.Integer(), nullable=True),
    sa.Column('split_screen_width', sa.Integer(), nullable=True),
    sa.Column('split_screen_height', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('photo_device',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('photo_id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['device.id'], ),
    sa.ForeignKeyConstraint(['photo_id'], ['photo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('photo_device')
    op.drop_table('photo')
    op.drop_table('device')
    # ### end Alembic commands ###
