"""Add photo_update_frequency and random_order to Device model

Revision ID: c7e6147d997f
Revises: 
Create Date: 2024-06-01 14:06:11.953731

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7e6147d997f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('device', schema=None) as batch_op:
        batch_op.add_column(sa.Column('photo_update_frequency', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('random_order', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('device', schema=None) as batch_op:
        batch_op.drop_column('random_order')
        batch_op.drop_column('photo_update_frequency')

    # ### end Alembic commands ###
